@hostname = rssaggregator.com
@apikey = 971038fa1f161602b3cd5685d99618b1467c48885d6c5ea0db0eea881fdc0a65

### Create user
POST http://{{hostname}}/users
Content-Type: application/json

{
    "name": "Teste here"
}

### Create feed
POST http://{{hostname}}/feeds
Content-Type: application/json
Authorization: ApiKey {{apikey}}

{
    "name": "Free code camp",
    "url": "https://www.freecodecamp.org/news/rss"
}

### Return feeds
GET http://{{hostname}}/feeds
Content-Type: application/json
Authorization: ApiKey {{apikey}}

### Follow feed
GET http://{{hostname}}/follow-feeds/1
Content-Type: application/json
Authorization: ApiKey {{apikey}}

### Unfollow feed
GET http://{{hostname}}/unfollow-feeds/1
Content-Type: application/json
Authorization: ApiKey {{apikey}}

### Return Posts
GET http://{{hostname}}/posts
Content-Type: application/json
Authorization: ApiKey {{apikey}}

